# Generated by Django 3.2 on 2021-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrhymocompanysiteapp', '0003_auto_20210608_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='Your_investment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
